INTERRUPT_PIN = 22
READ_PIN = 17
WRITE_PIN = 25

RING_UPSTAIRS = 0x109E8141
RING_DOWNSTAIRS = 0x009E8180
CANCLE_VOICE_CHANNEL_A = 0x3080
CANCLE_VOICE_CHANNEL_B = 0x2480
OPEN_DOOR = 0x109E8180
OPEN_VOICE_CHANNEL = 0x309E8100

TCS_REQUESTS = dict([
    (RING_UPSTAIRS, {
        'command': 'RING_UPSTAIRS'
    }),
    (RING_DOWNSTAIRS, {
        'command': 'RING_DOWNSTAIRS'
    }),
    (CANCLE_VOICE_CHANNEL_A, {
        'command': 'CANCLE_VOICE_CHANNEL_A'
    }),
    (CANCLE_VOICE_CHANNEL_B, {
        'command': 'CANCLE_VOICE_CHANNEL_B'
    })
])

WEB_SOCKET_COMMANDS = dict([
    (RING_UPSTAIRS, 'RING_UPSTAIRS'),
    (RING_DOWNSTAIRS, 'RING_DOWNSTAIRS'),
    (CANCLE_VOICE_CHANNEL_B, 'CANCLE_VOICE_CHANNEL_B'),
    (OPEN_DOOR, 'OPEN_DOOR'),
    (OPEN_VOICE_CHANNEL, 'OPEN_VOICE_CHANNEL')
])

WS_REQUESTS = dict([
    ('OPEN_DOOR', {
        'command': OPEN_DOOR
    }),
    ('OPEN_VOICE_CHANNEL', {
        'command': OPEN_VOICE_CHANNEL
    })
])