WS_IP = '0.0.0.0'
WS_PORT = 7700

INTERRUPT_PIN = 17
READ_PIN = 22
WRITE_PIN = 25

RING_UPSTAIRS = 0x109E8141
RING_DOWNSTAIRS = 0x009E8180 #0x009E8181 0x009E8182
CANCEL_VOICE_CONTROL_SEQUENCE = 0x3080
CANCEL_CONTROL_SEQUENCE = 0x2480
CANCEL_RING_CONTROL_SEQUENCE = 0x2400
OPEN_DOOR = 0x109E8180 #0x109E8181
OPEN_VOICE_CHANNEL = 0x309E8100
CONTROL_SEQUENCE = 0x5802

COMMANDS_TO_TEXT = dict([
    (RING_UPSTAIRS, 'RING_UPSTAIRS'),
    (RING_DOWNSTAIRS, 'RING_DOWNSTAIRS'),
    (CANCEL_VOICE_CONTROL_SEQUENCE, 'CANCEL_VOICE_CONTROL_SEQUENCE'),
    (CANCEL_CONTROL_SEQUENCE, 'CANCEL_CONTROL_SEQUENCE'),
    (CANCEL_RING_CONTROL_SEQUENCE, 'CANCEL_RING_CONTROL_SEQUENCE'),
    (OPEN_DOOR, 'OPEN_DOOR'),
    (OPEN_VOICE_CHANNEL, 'OPEN_VOICE_CHANNEL'),
    (CONTROL_SEQUENCE, 'CONTROL_SEQUENCE')
])

LONG_COMMANDS = {
    COMMANDS_TO_TEXT[RING_UPSTAIRS]: RING_UPSTAIRS, 
    COMMANDS_TO_TEXT[RING_DOWNSTAIRS]: RING_DOWNSTAIRS,
    COMMANDS_TO_TEXT[OPEN_DOOR]: OPEN_DOOR,
    COMMANDS_TO_TEXT[OPEN_VOICE_CHANNEL]: OPEN_VOICE_CHANNEL
}

SHORT_COMMANDS = {
    COMMANDS_TO_TEXT[CANCEL_VOICE_CONTROL_SEQUENCE]: CANCEL_VOICE_CONTROL_SEQUENCE,
    COMMANDS_TO_TEXT[CANCEL_CONTROL_SEQUENCE]: CANCEL_CONTROL_SEQUENCE,
    COMMANDS_TO_TEXT[CONTROL_SEQUENCE]: CONTROL_SEQUENCE,
    COMMANDS_TO_TEXT[CANCEL_RING_CONTROL_SEQUENCE]: CANCEL_RING_CONTROL_SEQUENCE
}