WS_IP = '0.0.0.0'
WS_PORT = 7700

INTERRUPT_PIN = 17
READ_PIN = 22
WRITE_PIN = 25

RING_UPSTAIRS = 0x109E8141
RING_DOWNSTAIRS = 0x009E8180 #0x009E8181 0x009E8182
CANCEL_VOICE_CONTROL_SEQUENCE = 0x3080
CANCEL_CONTROL_SEQUENCE = 0x2480
OPEN_DOOR = 0x109E8180 #0x109E8181
OPEN_VOICE_CHANNEL = 0x309E8100
CONTROL_SEQUENCE = 0x5802

COMMANDS = {
    'RING_UPSTAIRS': RING_UPSTAIRS, 
    'RING_DOWNSTAIRS': RING_DOWNSTAIRS,
    'CANCEL_VOICE_CONTROL_SEQUENCE': CANCEL_VOICE_CONTROL_SEQUENCE,
    'CANCEL_CONTROL_SEQUENCE': CANCEL_CONTROL_SEQUENCE,
    'OPEN_DOOR': OPEN_DOOR,
    'OPEN_VOICE_CHANNEL': OPEN_VOICE_CHANNEL,
    'CONTROL_SEQUENCE': CONTROL_SEQUENCE
}

LONG_COMMANDS = {
    'RING_UPSTAIRS': RING_UPSTAIRS, 
    'RING_DOWNSTAIRS': RING_DOWNSTAIRS,
    'OPEN_DOOR': OPEN_DOOR,
    'OPEN_VOICE_CHANNEL': OPEN_VOICE_CHANNEL
}

SHORT_COMMANDS = {
    'CANCEL_VOICE_CONTROL_SEQUENCE': CANCEL_VOICE_CONTROL_SEQUENCE,
    'CANCEL_CONTROL_SEQUENCE': CANCEL_CONTROL_SEQUENCE,
    'CONTROL_SEQUENCE': CONTROL_SEQUENCE
}

TCS_REQUESTS = dict([
    (RING_UPSTAIRS, {
        'command': 'RING_UPSTAIRS'
    }),
    (RING_DOWNSTAIRS, {
        'command': 'RING_DOWNSTAIRS'
    }),
    (CANCEL_VOICE_CONTROL_SEQUENCE, {
        'command': 'CANCEL_VOICE_CONTROL_SEQUENCE'
    }),
    (CANCEL_CONTROL_SEQUENCE, {
        'command': 'CANCEL_CONTROL_SEQUENCE'
    })
])

WEB_SOCKET_COMMANDS = dict([
    (RING_UPSTAIRS, 'RING_UPSTAIRS'),
    (RING_DOWNSTAIRS, 'RING_DOWNSTAIRS'),
    (CANCEL_CONTROL_SEQUENCE, 'CANCEL_CONTROL_SEQUENCE'),
    (OPEN_DOOR, 'OPEN_DOOR'),
    (OPEN_VOICE_CHANNEL, 'OPEN_VOICE_CHANNEL'),
    (CANCEL_VOICE_CONTROL_SEQUENCE, 'CANCEL_VOICE_CONTROL_SEQUENCE'),
    (CONTROL_SEQUENCE, 'CONTROL_SEQUENCE')
])

WS_REQUESTS = dict([
    ('OPEN_DOOR', {
        'command': OPEN_DOOR
    }),
    ('OPEN_VOICE_CHANNEL', {
        'command': OPEN_VOICE_CHANNEL
    }),
    ('RING_UPSTAIRS', {
        'command': RING_UPSTAIRS
    }),
    ('RING_DOWNSTAIRS', {
        'command': RING_DOWNSTAIRS
    }),
    ('CANCEL_CONTROL_SEQUENCE', {
        'command': CANCEL_CONTROL_SEQUENCE
    }),
    ('CANCEL_VOICE_CONTROL_SEQUENCE', {
        'command': CANCEL_VOICE_CONTROL_SEQUENCE
    }),
    ('CONTROL_SEQUENCE', {
        'command': CONTROL_SEQUENCE
    })
])