esphome:
  name: cerberus
  includes:
    - tcs_bus.h
    - cerberus.h

custom_component:
- lambda: |-
    auto cerberus = new Cerberus();
    return {cerberus};
  components:
  - id: my_custom_id

esp8266:
  board: esp01_1m

logger:

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-03Edeb"
    password: "sp9GO5BhJkt6"

captive_portal: