esphome:
  name: cerberus
  includes:
    - cerberus/esphome/include
    - cerberus/esphome/src

custom_component:
- id: cerberus
  lambda: |-
    auto cerberus = new Cerberus();
    return {cerberus};

button:
  - platform: template
    name: Open Door
    id: open_door
    icon: "mdi:key"
    on_press:
      then:
        lambda: getCerberus(cerberus)->onOpenDoor();

binary_sensor:
  - platform: custom
    lambda: |-
      return {getCerberus(cerberus)->ringingDownstairsSensor, getCerberus(cerberus)->ringingUpstairsSensor};
    binary_sensors:
      - name: "Ringing Downstairs"
      - name: "Ringing Upstairs"

esp8266:
  board: esp01_1m

logger:

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-03Edeb"
    password: "sp9GO5BhJkt6"

  use_address: "192.168.1.67"

captive_portal: