name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: uraimo/run-on-arch-action@v2
      name: Run commands
      id: runcmd
      with:
        arch: armv7
        distro: bullseye

        run: |
          apt update -y
          apt install -y sudo
          apt install -y python3
          apt install -y python3-pip
          python3 -m pip install pybind11
          apt install -y git-core
          git clone https://github.com/WiringPi/WiringPi
          cd WiringPi
          git pull origin
          ./build
          cd ..
          ls
          make
          python3 -m pip wheel -w dist .

    - uses: actions/upload-artifact@v3
      with:
        path: ./dist/*.whl
