name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: 'x64'
    
    - name: Install WiringPI
      run: sudo apt-get install libwiringpi-dev
      
    - name: Install pybind11
      run: python3 -m pip install pybind11
      
    - name: Make
      run: make

    - name: Install wheel
      run: python3 -m pip install wheel

    - name: Build wheels
      run: python3 -m pip wheel -w dist .
      # run: python3 -m cibuildwheel --output-dir dist
      # to supply options, put them in 'env', like:
      # env:
      #   CIBW_SOME_OPTION: value

    - uses: actions/upload-artifact@v2
      with:
        path: ./dist/*.whl
