name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: 'x64'
    
    - name: Install WiringPI
      run: sudo apt-get install wiringpi
      
    - name: Install pybind11
      run: python3 -m pip install "pybind11[global]"
    
    - name: Test pybind11
      run: python3 -m pybind11 --includes
      
    - name: Make
      run: make
