name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    
    - uses: uraimo/run-on-arch-action@v2
      name: Run commands
      id: runcmd
      with:
        arch: armv7
        distro: bullseye

        # Set an output parameter `uname` for use in subsequent steps
        run: |
          uname -a
          echo ::set-output name=uname::$(uname -a)
          apt update -y
          apt install -y python3
          apt install -y python3-pip
          python3 -m pip install pybind11
          apt install -y git-core
          cd
          git clone https://github.com/WiringPi/WiringPi
          cd ~/wiringPi
          git pull origin
          cd ~/wiringPi
          ./build
          make
          python3 -m pip wheel -w dist .

    # - name: Install pybind11n
      # run: python3 -m pip install pybind11

    # - name: Install Wiring Pi
      # run: sudo apt install -y libwiringpi-dev

    # - name: Make
      # run: make
      
    # - name: Build wheels
      # run: python3 -m pip wheel -w dist .

    - uses: actions/upload-artifact@v2
      with:
        path: ./dist/*.whl
