name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: 'x64'

    - uses: pguyot/arm-runner-action@v2
      id: build_image
      with:
        base_image: dietpi:rpi_armv7_bullseye
        commands: |
            sudo apt-get install libwiringpi-dev
            python3 -m pip install pybind11
            make
            python3 -m pip install wheel
            python3 -m pip wheel -w dist .

    - uses: actions/upload-artifact@v2
      with:
        path: ./dist/*.whl
