name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7l]
        include:
        - arch: armv7l
          cpu: cortex-a7
          base_image: raspios_lite:latest
          cpu_info: raspberrypi_3b

    steps:
    - uses: actions/checkout@v3
    
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: ${{ matrix.base_image }}
        cpu: ${{ matrix.cpu }}
        cpu_info: ${{ matrix.cpu_info }}
        commands: |
            sudo apt-get install libwiringpi-dev
            python3 -m pip install pybind11
            make
            python3 -m pip install wheel
            python3 -m pip wheel -w dist .

    - uses: actions/upload-artifact@v2
      with:
        path: ./dist/*.whl
